language: php
sudo: required
dist: trusty

php:
  - 7.0

env:
  - V8VER=5.2
  - V8VER=5.1
  - V8VER=5.2 VALGRIND=1

before_install: make -f Makefile.travis before_install
install:
  - if [ "$VALGRIND" = 1 ]; then sudo apt-get install -qq valgrind; export TEST_PHP_ARGS="-m"; fi
  - make -f Makefile.travis install

script: make -f Makefile.travis test
