# Configure and build scripts for travis CI system
V8VER ?= 6.3

IMAGENAME ?= v8js-test

export NO_INTERACTION=1
export REPORT_EXIT_STATUS=1

build:
	envsubst < Dockerfile.travis > Dockerfile.tmp
	docker build -t $(IMAGENAME) -f Dockerfile.tmp .

test: build
	docker run --rm -t $(IMAGENAME) make test
